FROM golang:1.21 AS builder
WORKDIR /app

# Dependency resolution
COPY go.mod go.sum ./
RUN go mod download

# Source copy
COPY . .

# Build step with static linking
RUN CGO_ENABLED=0 GOOS=linux go build -o /aoa_agent ./cmd/aoa

# Distroless runtime
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /aoa_agent .
USER 65532:65532

ENTRYPOINT ["/aoa_agent"]
