apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: audit-agent-hpa
  namespace: medusa-audit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: audit-agent
  minReplicas: 3
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
