apiVersion: v1
kind: Service
metadata:
  name: audit-agent
  namespace: medusa-audit
spec:
  selector:
    app: audit-agent
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  type: ClusterIP
