apiVersion: v1
kind: Service
metadata:
  name: correlation-agent
  namespace: medusa-orchestration
  labels:
    app: correlation-agent
spec:
  selector:
    app: correlation-agent
  ports:
  - name: health
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
