/// HOA approval gRPC client stub.
/// In full implementation, generated by tonic-build from api/proto/orchestration/v1/approval_service.proto.
/// Called by the AllocationEngine when a blueprint contains Tier 2 actions.
pub mod approval_client {
    use anyhow::Result;
    use tracing::info;

    pub struct HoaApprovalClient {
        endpoint: String,
    }

    impl HoaApprovalClient {
        pub fn new(endpoint: &str) -> Self {
            Self { endpoint: endpoint.to_string() }
        }

        /// Request a Tier 2 approval for a blueprint.
        /// Returns true if approved, false on denial or timeout.
        pub async fn request_approval(
            &self,
            blueprint_id: &str,
            action_id: &str,
            target_api: &str,
            pri_score: u32,
            trace_id: &str,
        ) -> Result<bool> {
            info!(
                blueprint_id = %blueprint_id,
                action_id = %action_id,
                pri_score,
                endpoint = %self.endpoint,
                "requesting Tier 2 HOA approval"
            );
            // Full implementation: tonic channel to HOA gRPC endpoint
            // with a context.WithTimeout of approval_timeout_secs.
            // Returns ApprovalResponse.status mapped to bool.
            Ok(true) // stub — always approves in dev
        }
    }
}
