/// Stub gRPC server for AllocationService.
/// In full implementation, generated by tonic-build from proto/allocation.proto.
/// Exposes GetBlueprint for AOA to query the latest blueprint for a crisis.
pub mod server {
    use tonic::{Request, Response, Status};
    use tracing::info;

    pub struct AllocationGrpcServer;

    impl AllocationGrpcServer {
        pub fn new() -> Self { Self }
    }
}
